# ----------------------------
# Minestore-BungeeCord by abhi
# version 1.0
# ----------------------------

# Websocket port to get orders.
Websocket-port: 25565

# Websocket password this password is required for website to run command
Websocket-password: "Mypassword"